var input = "^WWWWSWNNWWNWWNWSSWSSSSWNWWWNWNWSWWNWSWWSSSESWWSWSSSSENNESSSSENNNESSSSWWSSSWNWWWNENESENNWWWNE(NWNENWWSWWSESE(N|SS(E|SWSWSWSEENE(SENESSWSWSEENENN(EEENNNEENNNESEENENESEEESENESENENESESSWSWSESSSWNWSWWWWWWSWSESSSWNNWSWSWNNENNE(NWWSWS(WNN(NE(NWNEENNESENESSWWSES(WWNSEE|)E(S|NENNNN(EESWSEEESWSWS(EEEN(E(E|NNN(ENEWSW|)W(WW|SS))|W)|W(NNEWSS|)W)|W))|S)|WWSW(N|SESSSWWWSEEESSESSENEENESSWSEESWSEEENEESWSWWWWWNWSSWSSWSWNNENWWWSSE(SSSWSESWSEEEENEESSW(N|WWSWSWWWWSSWSSSSENNNEENN(WSNE|)ESSSSEES(WWWWNNES(NWSSEEWWNNES|)|EENENENNENNNNNW(NEEEESSSENNNEESSW(SSWWSSESWSWWN(ENWNENNW(NENWESWS|)S|WSSWS(EENEES(ENESENENNNWW(SESWWEENWN|)N(ENNESSESSEEEESWWSWS(EEEN(W|ENNEESSW(N|S(EEENWNENNW(S|NNWNEENNENEESSESENNWNEEEEEENENWWNENNESENNENNNEENESSESSSWNNWNWSSSWSSSW(NWES|)SSSW(WSEESWSSENENNESESENNENENESESSSWWW(NENESNWSWS|)SSWWN(W(SW(SWSSWNWWSS(WNNNNWNNEES(SSEEN(E|WNNNWNNWWSW(S(EENSWW|)SWSSE(N|SESSWS(E|WNWWWS(WNNENNNNN(ESSE(N|SSW(N|SEE(N|E)))|W(NENSWS|)SWSESS)|EE)))|N))|W)|E(EEEENESENNEEESWS(WNSE|)EEENNNW(WNN(WSSWWWSW(WSNE|)N|ESENENNEESSENNNWNENENENWWWWSWNWNENNNENNENNNNWSWWNENEENEESSSSEENEEESESESWWNWNWSWWWSSENEESWSSWSS(ESESEEESSSESWSEENESSWWSWSEESWSWS(EEEN(W|NEESWSEEEENEES(W|EENNW(WWWNWNENWNENNWSWWSESWW(SS(WNWESE|)ENESSSEN(SWNNNWESSSEN|)|NNNEENEENWWNNESEEEESSEEESWSWSEENENNNNWSWWNENWNWNWWNWWWNWWNNEEENWWNNESENNEENWWWSWNNWWWSESE(SSSWSSW(SESSESE(N(NWES|)EES(W|E(ES(E(E|N)|W)|N))|SWWWW(NWSWNW(S|NENWN(WSS(S|W)|N(N|ESENESSS(WNSE|)E(SEWN|)N)))|SSES(SENENE(NWW(S|W)|S)|W)))|NNNN(ESNW|)NWW(SESNWN|)WWWWNNNNWS(SSSS|WNWSWWSWWSWSWNNENNWNNENESS(W|EENEEENNEENWNNWSSWNWWNENWNNNESENNWNWSWNNENWWWWSESWWNNWWNNWWWNNNNWSSSWNWWWWSSESSSESESWSESWWNWSSSSSENNEEESSWW(NEWS|)SSSWSWSSWSWNWWSSE(N|SESSENNN(W|ESSESSSWSEESWWSSSE(ENN(WSNE|)ENE(S|ENNWNEEENEEESSESSSSSESWWNWW(NN|WSSENESSE(SWWS(S|WWNNE(E|S)|E)|EN(W|ESE(NNNENNWNW(SSEWNN|)NNNWN(EESEES(ENSW|)WWSESEN(SWNWNEWSESEN|)|NNNN(E|WNNE(NNNWSWS(WNWSSWWSWNNNW(SSW(N|SW(N|S(W|EE(ESEEN(NESSEE(SWWWWSE(EEEENN|SWWNNWNWS(WNSE|)SESWSES(SEWN|)W)|NNNWSS)|W)|N))))|NNESENENWNENWNW(WWW|NNEEESS(WNWESE|)ENNEEESESWSWNNWSSSSS(SWW(WSSWNSENNE|)NENWNNES(NWSSESNWNNES|)|ENNESSENNEENW(NENE(SSSSSWS(W(NNE|WS)|ES(S|EEN(NWS|ES)))|NWN(NN|WW(SESNWN|)WWNWSWNWSWWNNW(SS|WNEEEES(WSNE|)E(EE|NNWWWNWWW(N(W|E)|S(S|EE))))))|W))))|E)|S)))|ES(EE(ENEWSW|)SSWNWSSS(NNNESEWNWSSS|)|W))))))|SSWS(EE|WWNWWS(WNNNENNWWNWSSE(SWSESSWNWSS(E|WWWSWWWWNNWSW(NNNWSSWWNWNENE(SS|NENNESESWS(ESENEESEEENWWNWWWNNESEEESEENE(SSSW(N|SWWWWW(N|WW|SSEEN(W|EEE)))|NWW(WWNEENNNWSWNNNENNWNWNWNWWWWNNESEENN(ESSESESEEESW(SESWSES(EEENNE(NWNENENEENE(SSWWEENN|)NE(S|N(ESNW|)WWWWNEEENWWWNWWNNNWNNWWWNENNWWS(E|WS(SSE(SSSESWSSEESSSWW(NN(ESNW|)WW(SESNWN|)NNE(S|NWNEN(N|W))|SEEEEE(ENEN(E(S|E)|WNWSSWWNENWNEN(ESENSWNW|)NNWW(SESWWEENWN|)NWNEE(NWW|SE))|SWSSSW(SEWN|)NNN))|NN)|WNWNEENWWNNEES(W|EES(ENNEESWSEESESWS(WWNNES|SES(W|ENN(W|NEESSW(N|SSEE(SWSS(ENSW|)WNNWW(SE|NE)|N(EN(ESNW|)WNENWN(E|WNNE(S|NWNNWWNNNWNWSSSE(SWWNN(NNWNNEEES(ENEEENNWNNESESENESSENNEEEEESSENENNESSSESENNNNW(NWNWWNNNNWSSSSSE(E|S(WWWNWNWWWNENENWNWNNWNEESSENEEENWNENNENESSWSEESWSW(S(WWWS(SENESSWS(W(N|W)|SE(S|N))|W)|EENESENEEEESSWSEENNENNNWNNWNNWNNNESSENENEESESESSWNWSSSEEN(W|ESSSWSWWW(SSSSEEENNESSSWSSWNNWWSSE(N|SWSEESWSWWN(NNNWSWWSEESSWNWSW(NNNNENWW(NEEN(EESWS(EENNNN|S)|WWWNEN(E(S|N(W|E))|WWSW(N|SSE(ESNW|)N)))|S)|SSWSESWWSSWWWNWWWS(WWWNWNNNN(EESSEES(WSWNWNN(SSESENSWNWNN|)|ENESEESENNWWNWN(WNNWSSS(WNNNWS|E)|EE(SE(ESNW|)N|N)))|WNWSSESWWNWSW(SSSENESEE(NNW(WW|S)|SE(N|S(EENW|WWNWS)))|W|N))|EESWSSES(ENN(EN(EESSW(N|SW(N|SES(EENN(WSNE|)EEEEENWNNEEENWWNNNNESENESESWWS(WNSE|)ESSSWSSSSENESENNESEEESWWWSWSEESWSESENEEEENWNENENEESWSESENNEEENWWWNNNNENNNWWWNNWWSESSWSSEEN(W|NES(ENSW|)SSSWWWS(EEE|SWW(NENN(NWNNNNE(NNNNWSSSWSWSSSSWWWS(EEEE(ESWWWEEENW|)NNNN|W(SWNSEN|)NNNNEENE(SSWWSEE(WWNEENSWWSEE|)|NNNNWSSW(WNENW(NNN(W|EENWNEESSSENNNNESENNNEENWWNWSSSWNWNW(SSSENSWNNN|)NW(NEEE(S(S|W)|NWWNENNW(NWNENWNENWW(S|NNWNWSS(ESNW|)WWNENWWWWNNNNWNENWWNEENNEEESESWWSW(NNEWSS|)SSSEEENNN(WSSWNSENNE|)EENESSSEENEESWSSSSSESSW(SSEEN(NENEENWNNEEEEEEENESESSESEEEEE(SSSSSWSWWWWWSSENEESWSSESSEENE(SSSWSESSWSWSWNNWSSWSEESENEE(SSW(SESSSSWNNNWWSSSSWSWNNNWWSESSSEEENEEN(WNNNSSSE|)ESSSSWSWSEE(SWSSSE(NN|SWSWSSENE(SSSWWN(E|WSWNNWNENNE(NNWSWNWSWSSE(ENWESW|)SWWNNWNWN(WSWW(WSSWWSSWNWNEN(NEESWENWWS|)WWWSWWSW(NWNENWNENNE(NWWWNWW(N(EENNNW|WWS(WNSE|)E)|SES(SE(NESNWS|)SSSSS(W(NWES|)S|E)|W))|SESS(W(SEWN|)N|E))|SES(SEESWSSSW(SSEESES(WWWNEWSEEE|)ENNNEEES(EEENEESEESEENWNNNWSSWNWWNWNNWNWWSSE(N|ESS(E|W(SEWN|)NWSWWWWNEEENNWWNW(SS(EE|WSSS(ESNW|)W)|NN(WW(NEEN|SE)|ESESENEENN(WSNE|)EENWNEESE(ESSWW(NEWS|)SS(WNNWSNESSE|)ESWSESENEEENWWNN(NESSEN(N|ESSSSESENEEE(NNWWWWSEEE(WWWNEEWWSEEE|)|SSSWNNWSSSESE(N|SSSWNWN(NWWW(NNN(ESE(SWEN|)N|WN(N|E))|SSWNWN(E|WW(SSSESEN(NWNSES|)EEEE(NWNEWSES|)ESESE(N|SWSWSSWSWW(SEEESSW(SEENNE(NNNW(NENSWS|)S(W|S)|SSSWWSEESSSWNWN(E|W(NN|SSSWSWNNN(WSS(WNNWWW(NNNE(NNWSNESS|)SSENNE|SSEENW)|SSEEENESS(WWWW|EENNNW(WNSE|)SS))|E(N|S)))))|N)|NENNE(S|NN(ESNW|)WN(E|WWSES(E|SWNWSS(E(E|S(W|S))|WNW(WNNE(NWW(NNESNWSS|)SSSWNWW(EESENNSSWNWW|)|E(SWEN|)E)|S)))))))|NWW(WW|N))))|E))))|W(SS|W))|N)))))|WW)|WW(NEN(W|E(S|N))|WWWSWWWSE(WNEEENSWWWSE|)))|W))|NN(ESNW|)N)|EE(NWNEEEES(WWSNEE|)ENNE(NNN(WSWNWS(SE(SWEN|)E|WWNW(S|NENE(SS|NWNNNWWWNEEENNWWNNNWNNEENENESSWSW(SESS(WNSE|)ESEN(NWNNE(NNE(NNW(NNWNWSSESWWSWNNENWNENWNENENWWSWSWWWWWW(NNENEESS(W(N|W)|EENENNNWWNENWWW(NEEENWNN(EES(EESWWSESWSEESWSSEEE(NNW(SWEN|)NNWNENNN(ESSESSW(N|SEENEEESE(NNWWWW|SWWS(WN(NE|WWSE)|E)))|WW)|SSSS(WNSE|)EE(NWES|)S(W|SE(N|S(ESE(NEWS|)SS(E|WWN(E|N)|S)|W))))|W)|W)|SW(SWWWSEE(SWSSNNEN|)EENE(N|SEESWS)|N)))|SEEEES(ENESSSSSWWSWW(SEEE(NEEWWS|)SSWSW(NWSWNN(EEE|W(NEWS|)SSSW(SESWSNENWN|)NWWWNE)|SEENESSS(WWN(WSNE|)E|EE))|NNE(ENNESS|S))|WW))|S)|SS)|S)|EESS(EENWESWW|)W(SWW(NEWS|)SEEE(SS|N)|N))|W))))|E(NESNWS|)S)|SSE(N|SSS))|S))|SSS))|N))|N)|N)|N(N|W))|NNWNN(E(N|S)|WSS(S(S|E)|W)))|NWWNENWWSSWNWNNWNEES(EEENWWNNESEE(SSSS|NNW(S|WWWWNNESEEENWWNEEE(NWNNNE(SS|NNWWNNNESE(SWEN|)NNNNWSSWWWWSWWNENENWN(EESEE(SWWEEN|)N(W|EE)|WSSWWSESWWWSSEEESSSSWNWWSSE(ESWSWSEENESENNENW(WSNE|)NNNNNN(EEEE(NWES|)SWSESWSESSWS(EENNNNE(WSSSSWENNNNE|)|W(NN(E|NW(S|NNE(NWES|)S))|S(WSSSSEESWWWWNENWWSSS(EE|WNNNWSWWNNNNE(N(E|WWSSWNNNEENWNENE(N(ESEENW|WWNNNEE(SWSEWNEN|)NWNWNN(WWSESS(SSWSESS(E|SWNNWNWWWWNWSWSSENEESSSEEE(NNWNWSSE(WNNESEWNWSSE|)|E(E|SWSWSSWWW(SS(S|EEN(W|EENE(SEESSSWWW(NEENWWW(EEESWWEENWWW|)|SES(ENESEENN(WS|ESSEE)|WSS(WNNNSSSE|)E(SWSNEN|)N))|N(N|W))))|NNN(ESE(SW|NE)|NWWN(EENSWW|)WNWWNENWNNWSSSWWNENNWWNNESENEENN(WWWWS(EEE|WWWSSSWNWNWSSWNWWSSE(ESWWWNNNNENEE(SWEN|)EEE(S|N(EEE|WWWWWWSWNWSSWSEE(SSWSESSWSSSSESWSWWSSSESSWNWSSEEESEEESSWWWN(EE|WSSWSWWWWWSESSSEENWNEESSSSSSWWWWNNWWSSE(SSSESWWNWNN(ESNW|)NWNNNWNNNNNWSSSWNNWNWSSSWNNWNWSSSSSSESESWSESESWSEEESENEE(SWSSWNWWNWSSSWNNNWWNENWN(WWNENN(ESSNNW|)WSWSSWNNNWSWSSSSSENN(EEEESSSESE(N|SWSWSEESWS(EES(ENEENNWSWNN(W(W|SS)|EEEEEN(WWWNWS|ENEENN(ESSSSENE(NNEEEE(SWS(WNWSNESE|)ES(W|EEN(ESEWNW|)W)|NENWNNWSSWWWS(EEE|W(SS|NNNN(WSNE|)ESSENNE(ENNNEES(ENENWWWWNENNN(W(SS|WWW)|NESEESSS(ESE(SWSSWN|NENNWSWNNNEENNNW(SSWWW(SEWN|)W|NNENWWSWWNENNENESES(ENENWNNWWWNNW(NNW(NENEN(EEEENN(WSNE|)(N|ESSEENN(WSNE|)E(E(E|SWSSE(SWWNWSSWWWNEN(ESNW|)WWWSESWW(N|SEEEEESENENEEENEE(NWWEES|)EESESSEE(NWES|)SSWNW(SS|WNWN(WW(NEEWWS|)S(WWW(NEEWWS|)SS(ENSW|)WSSWNNN(ENSW|)WSW(SESSEESSSWSWSWW(N(NE(S|N(W|NES(ENSW|)S))|W)|SESSW(N|S(WW|EENNNESENN(NENE(NWNNSSES|)SSSES(ENESSNNWSW|)WSSSWSESESSESS(ESNW|)WNWWWNEENWWWNNN(E(SSEWNN|)NWNEE(S|NNN)|WWWSEESSSESSEEE(WWWNNWESSEEE|))|W))))|NWN(WSWNSENE|)E)|E)|E)))|N))|NWNNES))|W)|S)|SSS(EEESNWWW|)W(WS(WNSE|)E(SWS(S|E)|E)|N))|WW)))|WNW(NEWS|)S))|W)|SS))))|SSSS(WWNWN(EESNWW|)WW(NENESNWSWS|)SES(E|WWSWNW(SSW(NWSWENES|)SEENES|NEN(ESNW|)W))|E))|WSW(WSNE|)NN)))|W)|WNWWNWNENNWWWN(EENESE(NNWWEESS|)SESWSS|WWNWNWSWSSWSWNWNWNNWNNENWWWNNWSWSSSSWWWNNNENNWWS(WNWNNWWWSSWWWNNNNWWSWSESWWSEEE(NNN|SEESWSWSESSSSSWSSWNNWNENNE(SS|NWNNWWNWSSW(SSESSW(N|SEE(SSE(N|SSSWNWN(W(NENWESWS|)SSESESWW(SESSW(SSSESWSSENENESSWSEESWSESEESSWSWNN(WSWWSESSWNW(SSEESENNN(ESSESESEESWSWSSWWSSWNWWW(NNNENEEN(E(SSS(ENN(N|E)|WW(WSEE|NE))|N)|WWNWSS)|SSENESEESENNNESSSESWSSESWWSSESWWSWWNNNWSW(SESWSSESESWSW(NN|SSSSENNEN(EEEEENNNNWNN(WSWSESSWW(N(NWN(W|E)|E)|S(EEENNSSWWW|)W)|ENNEESSW(S(EENENNNNWS(WNNW(SSWWEENN|)N(W|EEENWWWNNNW(S|NENN(WSNE|)EN(NNNNEENWNEESESSESEEESENNN(WWS(WNNW(S|NWNWNEENWNWNNWWNEEESES(W|EEE(SE(N|ESWSWWN(W(SS(W|E(S(S|W)|E))|N(E|W))|E))|NWWNENWNWS(S|WWWWNWNNWWSSE(N|SSSWWNN(ESNW|)NWS(WNNENNNENNWWS(E|SWNNN(WSSSS(WNSE|)ES(ENSW|)W|EEENESEESENNEEESSWSEESWWSESEES(WWWS(E|WNN(W(NNN(WWW(NEWS|)SS(WSS|ENES)|E(NNEWSS|)SS)|S)|E))|ENEESSE(EEENWNNNNWWNNNENNWSWSWNNNWNWWWNWWNWSWNWW(NNNESENNNWW(SEWN|)NEEENNESESWSSW(SSS(ENNESSES(ENNNN(W(SS|WNEENWNN(ESNW|)WNWNNWSSWSSW(W|NN))|ESEEEEEESSWSWSSS(ENEEESENENN(WSWWW(W|NEEN(E|NW(NNWWNNN(ESSNNW|)W(N|SSSWWW)|S)))|ESSEEESWSSS(E(S|ENEENNEN(ESSSW(N|SW(SEENE(SSWWEENN|)NENNWS|W))|NNWN(WSWWS(EES(ENSW|)SSW(WSNE|)NN|WWNEN(W|NNESE(SWEN|)E))|EE)))|WNNNWSW(N|WWWNWSSEEESENESSWWSWNNWSS(WWNENSWSEE|)SSES(ENNW|WSE))))|W(NNW(S|NWW(NNEES(W|E(S|EN(W|E)))|S(W|E)))|S)))|W)|WW)|N)|SW(N|SEE(N|SESWWNWSS(WW(S(WNSE|)E|NENNWS)|EESENENNN(W|ESSSEENWN(EESSSENE(NWNSES|)SSWWSEESWSS(ENEE(NNNWSS|S(ENESSWSE(WNENNWESSWSE|)|W))|W)|N))))))|SWW(N(N|W)|S)))))|SSSEEEE(NNN|SWWSSESWSW(N|WSESENE(SSWENN|)EN(NNESENN(E|NW(NE|SWW))|W)))))))))|E)|E(SSSSWSESSWSESSEESWWWWSESSSSSESWWSWWSSSEEESEESWSSS(ENNEEN(ESENEWSWNW|)WNNE(NWWW(SEWN|)WN(WSWNSENE|)NESEENE(S|N(ESNW|)NNNNWSSW(SESWSNENWN|)WNNNNEEES(WWSSNNEE|)ENNNEN(ESSESSWS(W(W|NN(N|E))|EENNNE(SEWN|)N)|NNWSWS(E|WNN(E|W(NENWNNESEEENW(N|W)|SS))|SS)))|S)|SSSSWNNNWWWSSEE(NWES|)SS(EE|WNWWS(WWWNWSWWNNWSWWS(WWWNWSWNNNNESES(W|ENNNN(WSSNNE|)NESESSW(SS(SWEN|)ENE(S|ENEES(W|ES(WSNE|)ENNESSSENNE(NNNENNN(WWWWNENNN(WSWWSW(SEE(NEWS|)SWWSEEESWWWSEES(WWWNNW(SSS|W)|S|EEN(W|NNES(ENSW|)SSS))|N)|ENE(EENWWWW(S|NNNESES(W|EENNE(NWNWNNE(EENWWNENN(WNENWNWWWNWSWW(SSSSEEESEE(N(E|WNENWWWS(WNNEEEE(WWWWSSNNEEEE|)|E))|SWWSSE(SWS(EES(W|S)|W(NNNNNWSWS(E|WNN(NN|E))|WW))|N))|NEN(ENSW|)W)|E)|S)|SSS)))|SSWSESW(ENWNENSWSESW|)))|ESSSS(EENNW(N(E|N)|S)|W))|S)))|N))|EE)|E)))|E))|W)))|SS)|W)|N))|W))|NNEENENWNN(ESEESSW(SSSW(NN|S)|N)|WSW(SSENSWNN|)N)))|N)|NNNNESEN(NNWW(SE|NE)|E))|E)|N)|N)|E))|NNNE(NW(NEWS|)W|S)))|NNNE(NNNW(SS|NENE(ENWWW(S|NNNEESEEENNNEEEEESWWWWSSSS(WWN(WWWNSEEE|)E|ENNESENN(ESSENNNNEESSESESSSSSS(EES(ENNWNW(S|NEESEESS(WNSE|)ESENNEESEENNEESSW(N|SEENEES(ENENNENNNNWSWNNWSSSES(ENSW|)SWS(WWNEN(E|NNNNNNWNEEESEESW(WWNSEE|)SEEESSE(NNENEEENWNWWS(WSWWNENENENENNNWSWNNWNNEES(SEENNW(NNNWWSWWWNENNES(EEENESENNENWNNWSSSWWNNE(NWWSWNWWSWSWNNNWWNWSSESSE(NN|SSEES(ENN(NE(ES(W|E(SEWN|)N)|N)|WW)|WWWNNWNNWSWNWNENNE(SS|NWN(EEEEEESS(WNW(WW|S)|ENNEESWSS(WWSNEE|)EEENW(NNEEESEEESENN(WWW|ESSSESWSWNWN(E|W(WN(WW(SE|NW)|E)|SSESESWSWSESWSWS(WNNEWSSE|)SESESSWW(N(N|E)|SESSWS(W(W|NN(E|NN))|SENESSWSES(EEESSENESE(SESWWNWSS(WNNSSE|)S(EEN(W|ESESEE(NW|SWW))|SS)|NNENNEESS(WNSE|)ENE(S|NE(S|N(WW(S|NWNNWSWWWSWNNNEEE(SWWEEN|)NNWWNENWWWNNNNNESSSSEENNNW(SS|NNESEENNNWWWNNW(NWNEN(ESES(W|ESS(WNSE|)EESESSEESE(N(E|NNWW(SEWN|)NE(EE|NNNWWN(EEESNWWW|)WSSS(WNNWN(E|W)|E(NESNWS|)S)))|SSSSWS(E|WSWSSE(N|SW(SS|WWNNNNNES(ENENWWNENN(ESES(W|S)|W(SWWSS(ENSW|)SSS|NN))|SSS))))))|W)|SSS(EEESNWWW|)W(S(W(SSW(N|SSE(SSSSEE(NWES|)S(WWW(SWSEEE(NWES|)SSSSWW(NENNW(W|S)|SEEEE(SWEN|)NE(S|N(WWSNEE|)NEES(W|E)))|NNNWN(N|E|W))|EE)|N))|N)|E)|N))))|E))))|WWW(S|W)|S))))))|W))|WWWWWWWSESSSWSESSSWNWN(E|NWSWNNWNENNN(WSWWN(E|WWSESWWWNN(ESNW|)WSWWN(WWSSE(N|SSWWSESENESSSENNNNWNNEES(W|ESSW(SSENENNESSSWSSEEN(NESSSSESSWWWWNENE(SEWN|)NWWWNW(NEWS|)WWSWNWWNN(EESWENWW|)WN(E|NNWSWSESWSSENESSWWW(NNNNNNNE(NENEN(WWWS(E|S)|ESSS(E|W(N|W)))|S)|SSENESESENESESWWSEEENNNESENN(W(NEWS|)WW(S|WW(NEWS|)W)|E(SSSWWSSSWSWSWNWWWWNENNN(WSW(NNEEWWSS|)S(E|SSSSSESS(WNSE|)ENNNEN(WWSNEE|)ESES(WSSSWNNN(SSSENNSSWNNN|)|EEN(EN(NEEEESSS(WWNENWWSSW(ENNEESNWWSSW|)|EENWNENWNEEENNEEENESSSENNNENWWNEENESSSEEENWNNNNNWSS(SSS|WNNNW(SSSWSWNWN(EE|NWSWWNN(NW(SSSSEEESSE(SWSWW(WWWWSS(ENESEN|SWNWW(SE|NEEN))|NENWNE)|N)|N(E|NWW(SSENSWNN|)N(EEN(E|W)|WW)))|E(S|E)))|NNNNEEE(SWWSES(W|E(S(E(SENESSSWNWSSSEEN(EN(EESWSSEESWWWWSW(NNEENSWWSS|)SEESSSS(ENNEEEENWNN(NEE(SS(WNSE|)SE(N|SS(ENEWSW|)SWWW(SEEWWN|)N(WSWN|EEN))|NN(EEENSWWW|)WSWNW(NENWESWS|)W)|WSWW(SEEWWN|)N(E|W))|WSWSWSEE(N|ESSSSWWS(WWS(WNNWWWNNESEEENN(NWSSWNNWSWNNNESEEENWWNNWSWWWNWNW(SSWNNWSSSESSESW(WNNWSNESSE|)SSSENEES(SE(EES(WS|EN)|NNNWNENNNWW(S(WNSE|)ESWSSW|N))|W)|NEE(NWWEES|)SESENENENEESSSW(N(W|N)|SEE(NE(S|NWN(EESSNNWW|)NNWWWWS(NEEEESNWWWWS|))|S)))|ESEE(SWWSW|NW))|S)|EE)))|NN)|W)|N)|W)|N))|NE(S|NWWSWNWS(NESENEWSWNWS|))))))|W)|W)))|ESSSEEEN(E|WW))|E))))|W)|N)))|E))|ESSE(ESWSWN|NN)))))))|S)|S)|S)|W)|E)|SWSW(NNN|SEE(SWS(W(NWSNES|)S|E)|N))))|E)|WSSWWSWNWSWNW(SS(EES(WS(ESW|WN)|ENEEEN(E(NN|SS(S|W))|W))|W)|NN(ESE(EEE|N)|W(SWWEEN|)N)))))|SSSSWN)|WNNW(NWSWNN(WWWSS(EENWESWW|)W(SSENSWNN|)N|EEN(ESSNNW|)WN(E|NN))|SS))|WW)))|SS))|EEES(W|E)))))|E))))|NN)|E)|NWWNEN(ESNW|)NNWWNE(NWWWS(ESSS(WNNSSE|)SSENNENW(ESWSSWENNENW|)|WNN(W(NN|S)|EE(EE|NN)))|E))|N))|N)))|N))|EESSEESS(WNWSW(N(NN|WW)|SE(SS|E))|ENNNN(WSWNSENE|)ESENEESWSWSSS(WNNNSSSE|)EENWNENESS(NNWSWSNENESS|))))))))|E)|ESENEEEESWWWS(ESWENW|)W))|SSS))|SS(EEEEE|S)))|E)))|WWW)|N)))|SS)))|S))|W)|NWNW(NWNWWN(NE(NWNEWSES|)SENEESS(WNSE|)S|WSWNWSWN(SENESEWNWSWN|))|S)))|S))|WWWSESW(ENWNEEWWSESW|)))|WSWWWWWSW(SSSWSEE(SSSWWWNN(ESENSWNW|)NN|NE(NWNENSWSES|)S)|N))|S(E|S))))|S(E|SS))|EEE)|S(SWW(SEEWWN|)N(E|W)|E))))|W)))|W)|W)|W)))|E))|NEEN(WWNWNENWWNEEN(E|N|W)|E))))|N)|S))|SS)|WW)|WSSWWWWWS(WWWSESSSSWWNWWWSW(NWSWWWWS(E(E|S)|WNNNESEENNW(NNEEEN(WWNWSWSSWS(W(SW(SEWN|)W(NEWS|)W|NNNWNEE(E|SS))|E)|ESEEENE(SSWSS(EE(NWES|)S|WWNN(ESNW|)WSSWW(S|NN(ESNW|)W))|NESENE(EEENESEN(SWNWSWENESEN|)|S|NWWN(NWSWS(E|S)|EE))))|S))|SEENESEE(WWNWSWENESEE|))|EEE(SWEN|)EEEESEEE(NWWEES|)SSSWNNW(W|S)))|N)))|W))))))|W)))))|SSSESSEEE(N(ENSW|)WWNNWN|SSWW(WWN(NNWNWWWSSENESESWWW(EEENWNSESWWW|)|EEE)|SEESSS(S|E|WW(NENWESWS|)W))))|WW)|W)|W(WWWWWSESE(SWW(N|SSSWSWW(SES(W|S(EENWNENENNNESSENNESSSWWSEEESWWSW(NW(S|N)|SSS(WSS(ENSW|)SWWS(E|WWSSS(ENE(SE|NW)|WNWWS(WWNEN(WWSSSE|NEEE(SWWEEN|)NWWNEEEN(ES(ENES|SW)|WW))|E)))|ENEN(NEEENE(SSS(EE|S(WNWSW(NNEEWWSS|)(W|S)|S))|NWW(S|NNW(S|NE(NWES|)ESSE(E|N))))|W)))|S))|NEN(E|W(N|WSWWN(E|WW(SESEWNWN|)NEENWN(W(NN|S)|E))))))|N)|S))|S))|W))|SES(EESESSS(WNNW(NWSNES|)SS|ENESEN(ESNW|)NNN(NESENSWNWS|)WW(SESWENWN|)W)|W)))|E)|E))))))))|N))|S)))|WNWWNWSS(EE|WNNNNENESEE(N(NNWWWWS(EEESNWWW|)SW(SSWWN(W(NN|SSSES(EENNW(W|S)|WWNNNN))|E)|NNNEEEENWN(EESSNNWW|)W(WS(W|E)|N))|E)|SS(WNWWEESE|)E)))|WNWNW(NE(N(NNNNNN|W)|E(S|E))|WSES(E|W))))|SS)|N))|N)|N)|E)|N))|W)))|W(NNEWSS|)W)|W)|W)|W))|N)|SSSWWN(E|WSWSSSEE(ENN(WWSEWNEE|)E|SW(WWNNNSSSEE|)S)))))|N)))|E)|S)|N)|N)))|EE)$";
//var input = '^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$';
//var input = '^ESSWWN(E|NNENN(EESS(WNSE|)SSS|WWWSSSSE(SW|NNNE)))$';

// plan of action
// 1. input -> grafu
//                  7
//     2       5 <  8  >
// 1 <   > 4 <            > 9
//     3          6
//
// 2. ???
// 3. profit!

var tree = [{
    id: 0,
    parent: false,
    data: '',
    mode: 'AND',
    childs: []
}];

function getOrs(s) {
    var ors = [], depth = 0;
    for (var i = 0; i < s.length; i++) {
        if (s[i] == '(') depth++;
        if (s[i] == ')') depth--;
        if (depth == 0 && s[i] == '|') ors.push(i);
    }
    return ors;
}

function newNode(parentNode, mode) {
    var newNodeId = tree.length;
    var node = {
        data: '',
        id: newNodeId,
        mode: mode,
        parentId: parentNode && parentNode.id,
        childs: []
    };
    tree.push(node);
    if (parentNode) {
        parentNode.childs.push(newNodeId);
    }
    return node;
}

function getCators(s, ors) {
    // return array of ors.length+1 strings
    var arr = [];
    for (var i = 0; i <= ors.length; i++) {
        var start = 0;
        if (i > 0) start = ors[i-1]+1;
        var end = s.length;
        if (i < ors.length) end = ors[i];
        arr.push(s.slice(start, end));
    }
    return arr;
}

function getTopLevelBrackets(s) {
    var arr = [], depth = 0;
    for (var i = 0; i < s.length; i++) {
        if (s[i] == ')') depth--;
        if (depth == 0 && (s[i] == '(' || s[i] == ')')) arr.push(i);
        if (s[i] == '(') depth++;
    }
    return arr;
}

// kompletne predelat parsing
// 1. je na danym levelu "|" ? pokud jo, udelat novou nodu v modu OR jejiz childy budou jednotlive ORance (poslat parse tech ORancu)
// 2. je na danym levelu ()? pokud ne, je to simple value
//    - pokud jo, rozlozit A(B)C(D)(E) na ANDance, to budou childy nove nody v AND modu, poslat parsing tech ANDancu
function parseNew(data, parentNode) {
    //console.log('********* parsing', data);
    var ors = getOrs(data);
    if (ors.length > 0) {
        var cutOrs = getCators(data, ors);
        //console.log('ORS', cutOrs);
        var node = newNode(parentNode, 'OR');
        cutOrs.map(s => {
            parseNew(s, node); // prazdne stringy vitany
        })
        return;
    }

    if (data.indexOf('(') > -1) {
        // we hv A(B)C(D)(E)
        var ands = getTopLevelBrackets(data);
        var cutAnds = getCators(data, ands);
        //console.log('ANDs', cutAnds);
        var node = newNode(parentNode, 'AND');
        cutAnds.map(s => {
            if (s.length > 0) parseNew(s, node); // tady prazdne stringy nechceme
        })
        return;
    }

    var node = newNode(parentNode, ''); // leaf
    node.data = data;

}

var root = $('#root');
var pre = $('<pre>');
root.append(pre);

function renderMap() {
    pre.empty();

    for (var y=0;y<mapSize;y++) {
        var line = '';
        for (var x=0;x<mapSize;x++) {
            line = line+(map[y][x] ? (map[y][x] == '?' ? '#' : map[y][x]) : ' ');
        }
        pre.append(line);
        pre.append('<br>');
    }
}

parseNew(input, tree[0]);
console.log(tree);

//buildPaths('', tree[0]);
//console.log(paths);

//console.log(findAPath('', tree[0]));

var map = [], mapSize = 500; //[y][x]
for (var y=0;y<mapSize;y++) {
    map[y] = [];
    /*for (var x=0;x<mapSize;x++) {
        map[y][x] = '?'
    }*/
}

var startX = mapSize/2, startY=mapSize/2;
map[startY][startX] = 'X';

var minx = 0,miny = 0,maxx = 0,maxy = 0;

function drawNode(node,x,y) {
    minx = Math.min(minx,x);
    miny = Math.min(miny,y);
    maxx = Math.max(maxx,x);
    maxy = Math.max(maxy,y);
    console.log('drawing node', node);
    //console.log('boundaries', minx, miny, maxx, maxy); // -29, -19000 9545 125 asi je neco spatne
    for (var i=0;i<node.data.length;i++) {
        var ch = node.data[i];
        if (ch == '^') continue;
        if (ch == '$') continue;
        if (ch == 'N') {
            y--;
            map[y][x] = '-';
            map[y][x-1] = '#';map[y][x+1] = '#';
            y--;
        }
        if (ch == 'S') {
            y++;
            map[y][x] = '-';
            map[y][x-1] = '#';map[y][x+1] = '#';
            y++;
        }
        if (ch == 'E') {
            x++;
            map[y][x] = '|';
            map[y-1][x] = '#';map[y+1][x] = '#';
            x++;
        }
        if (ch == 'W') {
            x--;
            map[y][x] = '|';
            map[y-1][x] = '#';map[y+1][x] = '#';
            x--;
        }
        map[y][x] = '.';
    }

    if (node.mode == 'AND') {
        for (n = 0; n < node.childs.length;n++) {
            var a = drawNode(tree[node.childs[n]],x,y);
            x = a[0];y = a[1];
        }
    } else if (node.mode == 'OR') {
        node.childs.map(nId => {
            drawNode(tree[nId], x, y);
        })
    }
    return [x,y];
}

function tree2string(s, node) {
    s = s + node.data;
    if (node.childs.length > 0) {
        var subs = [];
        node.childs.map(nId => {
            subs.push(tree2string('', tree[nId]));
        })
        var ss = subs.join( (node.mode == 'OR' ? '|' : '') );
        if (node.mode == 'OR') s = s + '(' + ss + ')';
        else s = s + ss;
    }
    return s;
}

function cmpStrings(s1, s2) {

    console.log('lengths', s1.length, s2.length, s1.length == s2.length);
    var matched = 0;firstMismatch = false;
    for (var i = 0; i < Math.min(s1.length, s2.length); i++) {
        if (s1[i] == s2[i]) matched++;
        if (s1[i] != s2[i]) {
            if (!firstMismatch) firstMismatch = i;
        }
    }

    console.log('matching characters count', matched, 'firstMismatch', firstMismatch);
}

var output = tree2string('', tree[0]);
pre.html(output);

cmpStrings(input, output);

/*
var input = '^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$';
             ^WSSEESWWWNW(S|(NENNEEEENN((ESSSSW(NWSW|SSEN))|(WSWWN(E|(WWS(E|SS)))))))$
             ^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$
*/

//drawNode(tree[0], startX, startY);
//console.log('boundaries', minx, miny, maxx, maxy); // -29, -19000 9545 125 asi je neco spatne
//renderMap();